Implement the caching mechanism  for the publisher restrictions in `TCData` class
didomi/iabtcf-es-archived pull request #4
Opened 2022-08-22 18:10 UTC by sevriugin

## Description  
To implement the caching mechanism we introduce two new classes: `CacheBucket` and `Cache` in the  IAB TCF `cmpapi` library. The `CacheBucket` class implements actual caching mechanism and provides `get` method that accepts cache key, recalculation function and recalculation functions parameters as arguments. The  `CacheBucket` class also has a `name` property and `Cache` class implements a collection (map) of `CacheBucket`  objects with several simple methods including the `getBucket` method to get `CacheBucket`  by the name. We need this two level structure to separate caching for two classes `TCData` and `InAppTCData` . 
## Summary of changes 
- `CacheBucket` class implemented;
- `Cash` class implemented;
- Update `CmpApiModel` class (singleton) to add `restrictionsCache` parameter;
- Update `TCData` class to use restrictions cache;
- Add unit and integrations tests.

2022-08-24 15:48 UTC, jawadst requested changes

2022-08-24 15:48 UTC, jawadst commented on modules/cmpapi/src/Cache.ts
> +    private cacheBuckets: Map<string, CacheBucket<Type>>;
What's the point of using Cache + CacheBuckets vs directly using CacheBucket? (and renaming it `Cache`)

The InAppTCData/TCData can simply create their own instance of CacheBucket to keep the caches separate.

2022-08-24 15:48 UTC, jawadst commented on modules/cmpapi/src/CacheBucket.ts
> +      this.recalculations = 0;
What's the point of recalculations?

2022-08-24 15:48 UTC, jawadst commented on modules/cmpapi/test/response/TCData.test.ts
> +    CmpApiModel.restrictionsCache.clear();
Can you move this to a separate test that is specifically designed to check whether the TC string comes from the cache or not? (rather than modify an existing one)

Should you assert on the restrictions (to make sure they are the same from the cache or not) or is TestUtils.tcModelToTCData() doing that?

2022-08-25 08:25 UTC, sevriugin commented on modules/cmpapi/src/Cache.ts
> +    private cacheBuckets: Map<string, CacheBucket<Type>>;
The point is that the whole logic of working with restrictions cache is implemented only in one place for all classes that could be extended from `TCData` class - `TCData` constructor.  So, if someone will create a new class inherited from `TCData` and overwrite `createResterictions` method this new class will be covered by cache mechanism implemented by the parent class.  

To separate instances we use `this.constructor.name` == `class name` and `Cache` class is responsible to create or access the instance of the cache (`CacheBucket`) for particular class (name) inherited from the `TCData`.  So in this case we are separating logic for creating / accessing cache instance by name and working with cache instance. 

I thought that it will be more elegant compare to the solution to have each class responsible to manage own instance of the cash or to have cache key constructed with  `this.constructor.name` + actual cache key (in our case `this.tcString`).

Hope it makes sense.

2022-08-25 09:16 UTC, sevriugin commented on modules/cmpapi/test/response/TCData.test.ts
> +    CmpApiModel.restrictionsCache.clear();
Test is moved, and yes, `TestUtils.tcModelToTCData()` is responsible for assertion

2022-08-25 09:31 UTC, sevriugin commented on modules/cmpapi/src/CacheBucket.ts
> +      this.recalculations = 0;
I have user [Reselect](https://github.com/reduxjs/reselect) as a reference library in this case. 

There is section in the library documentation [Q: How do I test a selector?](https://github.com/reduxjs/reselect#q-how-do-i-test-a-selector) explaining  "... a `recomputations` method that will return the number of times it has been recomputed".  

So, I have decided to implement this simple mechanism to improve testing / profiling experience for `CacheBucket` class.

2022-08-25 18:40 UTC, jawadst commented on modules/cmpapi/src/Cache.ts
> +    private cacheBuckets: Map<string, CacheBucket<Type>>;
That makes sense but how is it different from simply doing a `new Cache()` in the constructor? That gives you separate cache instances without conflict. You are separating it with different CacheBucket when you could simply separate by initializing different cache instances in the constructor, no?

2022-08-25 18:41 UTC, jawadst commented on modules/cmpapi/src/CacheBucket.ts
> +      this.recalculations = 0;
Ok that makes sense

2022-08-25 18:41 UTC, jawadst commented on modules/cmpapi/test/response/TCData.test.ts
> +    CmpApiModel.restrictionsCache.clear();
Thanks

2022-08-25 18:42 UTC, jawadst commented on modules/cmpapi/src/Cache.ts
> +    private cacheBuckets: Map<string, CacheBucket<Type>>;
I don't think that's a blocker if you want to move forward, you can merge as is. I am just not convinced of the value of the extra indirection that makes the logic a little bit harder to follow without providing actual value. Up to you though.

2022-08-26 08:32 UTC, sevriugin commented on modules/cmpapi/src/Cache.ts
> +    private cacheBuckets: Map<string, CacheBucket<Type>>;
Thanks, I will move forward then. 

Regarding `new Cache()` in the `TCData` constructor it will create new `Cache` instance for each `TCData` instance, if I've understood the idea correctly, but what we really need - is to share `Cache` instance between all `TCData` objects, so we need to create `Cache` instance per class.

2022-08-26 14:27 UTC, jawadst commented on modules/cmpapi/src/Cache.ts
> +    private cacheBuckets: Map<string, CacheBucket<Type>>;
Oh ok that makes sense

2022-08-29 11:31 UTC, merged